// Load an equirectangular Earth texture and pre-render its gnomonic
// projection onto each polyhedron face. Result: one offscreen canvas
// per face, with the Earth's surface mapped through the face plane and
// clipped to the face polygon (triangle/square/pentagon depending on
// the polyhedron type).
//
// The display side (modes B / C / D) maps each offscreen canvas onto the
// destination polygon with a 2x3 affine via ctx.setTransform.

// Earth representation registry. Each entry is either:
//   - a styled SVG preset (svgStyle present) that we rewrite on load, or
//   - a raster URL (svgStyle absent) loaded as-is.
// The blank-equirectangular SVG (Natural Earth-derived; CC0) has one
// <path> per country wrapped in <g class="country XXX"> where XXX is the
// ISO 3166-1 alpha-3 code, so we can target Antarctica/Greenland by class.
const BLANKMAP_URL = './assets/BlankMap-Equirectangular.svg';

const OUTLINE_STYLE = `<style type="text/css">
    .country { fill: none; stroke: #5c3d2e; stroke-width: 0.25; stroke-linejoin: round; }
    .country.ATA, .country.GRL { fill: #d6c89c; fill-opacity: 0.7; stroke: #5c3d2e; stroke-width: 0.25; }
</style>`;

// Bare-outlines variant: country borders only, no Antarctica/Greenland fill,
// no Arctic ice strip. Reads as a clean line-only world map suitable for
// overlay with elevation contours.
const BARE_OUTLINE_STYLE = `<style type="text/css">
    .country { fill: none; stroke: #5c3d2e; stroke-width: 0.25; stroke-linejoin: round; }
</style>`;

// Solid land - continents read as unified blobs (no inter-country borders).
// Antarctica and Greenland get the same ice fill the Arctic strip uses, so
// the polar regions look like a single ice cap.
const SOLID_STYLE = `<style type="text/css">
    .country { fill: #5a7a4a; stroke: none; }
    .country.ATA, .country.GRL { fill: #c8d8e8; stroke: none; }
</style>`;

export const EARTH_PRESETS = {
    outlines: {
        id: 'outlines',
        label: 'Outlines',
        url: BLANKMAP_URL,
        svgStyle: OUTLINE_STYLE,
        paintArctic: true,
        arcticAlpha: 0.55,
    },
    bare: {
        id: 'bare',
        label: 'Bare',
        url: BLANKMAP_URL,
        svgStyle: BARE_OUTLINE_STYLE,
        paintArctic: false,
    },
    continents: {
        id: 'continents',
        label: 'Continents',
        url: BLANKMAP_URL,
        // svgStyle is kept so the path loader recognises this as an SVG
        // preset; the actual raster is generated by rasterizeContinentsImage()
        // below since the SVG's CSS can't hide country-shared borders.
        svgStyle: BARE_OUTLINE_STYLE,
        dedupeEdges: true,   // strip border segments that two countries share
        paintArctic: false,
    },
    solid: {
        id: 'solid',
        label: 'Solid',
        url: BLANKMAP_URL,
        svgStyle: SOLID_STYLE,
        paintArctic: true,
        arcticAlpha: 0.95,
    },
    // NASA Blue Marble equirectangular (Reto Stockli / NASA GSFC). 2048x1024,
    // CORS-open on upload.wikimedia.org. Realistic biome/terrain coloration
    // including the polar ice caps, so no Arctic painting needed.
    terrain: {
        id: 'terrain',
        label: 'Terrain',
        url: 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Land_ocean_ice_2048.jpg',
    },
};

export const DEFAULT_EARTH_PRESET = 'outlines';
const RENDER_SIZE = 256;
// Source SVG is a true vector file, but Modes B/C/D's per-face pre-renderers
// and Mode A's 3D globe texture need a raster. Mode A-2 now uses per-face
// vector path rendering directly (so it doesn't sample this raster), so this
// only needs enough resolution for the 256x256 per-face canvas sampling done
// by preRenderEarthFaces — 2048x1024 RGBA = ~8 MB getImageData, fast to
// rasterize and process on first load.
const SVG_RASTER_W = 2048;
const SVG_RASTER_H = 1024;
const ARCTIC_LAT_DEG = 66.5;
const POLAR_ICE_RGBA = (a) => `rgba(200, 216, 232, ${a})`;

export async function loadEarthImage(presetIdOrUrl = DEFAULT_EARTH_PRESET) {
    // Accept a registry ID, a raw URL, or undefined (=> default preset).
    const preset = (typeof presetIdOrUrl === 'string' && EARTH_PRESETS[presetIdOrUrl])
        ? EARTH_PRESETS[presetIdOrUrl]
        : { url: presetIdOrUrl };
    if (preset.dedupeEdges) {
        // SVG's inline CSS can't selectively hide country-shared borders, so we
        // bypass loadAndStyleEarthSvg and render the deduplicated paths to a
        // fresh equirectangular canvas with our own renderer.
        const pathData = await loadEarthSvgPaths(preset.id);
        const style = PRESET_PATH_STYLES[preset.id] || PRESET_PATH_STYLES.bare;
        return rasterizeContinentsImage(pathData, style, SVG_RASTER_W, SVG_RASTER_H);
    }
    if (preset.svgStyle) return loadAndStyleEarthSvg(preset);
    return loadRasterImage(preset.url);
}

// Render the deduplicated SVG paths (from loadEarthSvgPaths with dedupeEdges)
// to a global equirectangular canvas. Segments whose canonical-key appears in
// multiple country paths (i.e. shared country borders) are skipped, leaving
// only the coastline / land-water boundaries.
function rasterizeContinentsImage(pathData, style, w, h) {
    const canvas = document.createElement('canvas');
    canvas.width = w; canvas.height = h;
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = style.bgColor || '#ffffff';
    ctx.fillRect(0, 0, w, h);
    ctx.strokeStyle = style.stroke || '#5c3d2e';
    ctx.lineWidth = (style.strokeWidthPx || 1.0) * (w / 4096); // scale stroke with raster width
    ctx.lineJoin = 'round';
    ctx.lineCap  = 'round';
    const proj = (lat, lon) => ({
        x: (lon / (2 * Math.PI) + 0.5) * w,
        y: (0.5 - lat / Math.PI) * h,
    });
    for (const path of pathData.paths) {
        ctx.beginPath();
        let penDown = false;
        for (const pt of path.points) {
            const p = proj(pt.lat, pt.lon);
            if (!penDown || pt.move || pt.skipFromPrev) {
                ctx.moveTo(p.x, p.y);
                penDown = true;
            } else {
                ctx.lineTo(p.x, p.y);
            }
        }
        ctx.stroke();
    }
    // The 3D Mode A globe sphere uses the texture's `naturalWidth/Height` to
    // size its data canvas — mimic the existing rasterisation by exposing them.
    Object.defineProperty(canvas, 'naturalWidth',  { value: w });
    Object.defineProperty(canvas, 'naturalHeight', { value: h });
    return canvas;
}

function loadRasterImage(url) {
    return new Promise((resolve, reject) => {
        const img = new Image();
        img.crossOrigin = 'anonymous';
        img.onload = () => resolve(img);
        img.onerror = () => reject(new Error(`Failed to load Earth texture: ${url}`));
        img.src = url;
    });
}

async function loadAndStyleEarthSvg(preset) {
    const { url, svgStyle, paintArctic, arcticAlpha = 0.55 } = preset;
    const resp = await fetch(url);
    if (!resp.ok) throw new Error(`Earth SVG fetch ${resp.status}: ${url}`);
    let svgText = await resp.text();
    svgText = svgText.replace(/<style[^>]*>[\s\S]*?<\/style>/, svgStyle);
    // Force the SVG to render at our target raster size. The source declares
    // width/height=360x180; without this override, some browsers rasterize at
    // that native size and the canvas upscale would be fuzzy and clip strokes.
    svgText = svgText.replace(/<svg\b([^>]*)>/, (_m, attrs) => {
        const noSize = attrs.replace(/\s(?:width|height)="[^"]*"/g, '');
        return `<svg${noSize} width="${SVG_RASTER_W}" height="${SVG_RASTER_H}">`;
    });
    const blob = new Blob([svgText], { type: 'image/svg+xml' });
    const blobUrl = URL.createObjectURL(blob);
    try {
        const img = await new Promise((resolve, reject) => {
            const i = new Image();
            i.onload = () => resolve(i);
            i.onerror = () => reject(new Error('Styled Earth SVG: Image load failed'));
            i.src = blobUrl;
        });
        const c = document.createElement('canvas');
        c.width = SVG_RASTER_W;
        c.height = SVG_RASTER_H;
        const ctx = c.getContext('2d');
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(0, 0, SVG_RASTER_W, SVG_RASTER_H);
        ctx.drawImage(img, 0, 0, SVG_RASTER_W, SVG_RASTER_H);
        if (paintArctic) {
            const arcticY = SVG_RASTER_H * (90 - ARCTIC_LAT_DEG) / 180;
            ctx.fillStyle = POLAR_ICE_RGBA(arcticAlpha);
            ctx.fillRect(0, 0, SVG_RASTER_W, arcticY);
        }
        Object.defineProperty(c, 'naturalWidth',  { value: SVG_RASTER_W });
        Object.defineProperty(c, 'naturalHeight', { value: SVG_RASTER_H });
        return c;
    } finally {
        URL.revokeObjectURL(blobUrl);
    }
}

export function getEarthTextureUrl(presetId = DEFAULT_EARTH_PRESET) {
    return (EARTH_PRESETS[presetId] || EARTH_PRESETS[DEFAULT_EARTH_PRESET]).url;
}

// Render-style config for the per-face SVG path renderer. The per-face renderer
// cannot use the SVG's inline CSS (no DOM around face canvases), so we replicate
// the visual configuration here per preset. Keys align with EARTH_PRESETS.
export const PRESET_PATH_STYLES = {
    outlines: {
        bgColor: '#ffffff',
        stroke: '#5c3d2e',
        strokeWidthPx: 1.5,
        fill: null,
        antarcticFill: 'rgba(136,160,184,0.8)',
        greenlandFill:  'rgba(136,160,184,0.8)',
    },
    bare: {
        bgColor: '#ffffff',
        stroke: '#5c3d2e',
        strokeWidthPx: 1.5,
        fill: null,
        antarcticFill: null,
        greenlandFill: null,
    },
    continents: {
        bgColor: '#ffffff',
        stroke: '#5c3d2e',
        strokeWidthPx: 1.5,
        fill: null,
        antarcticFill: null,
        greenlandFill: null,
    },
    solid: {
        bgColor: '#ffffff',
        stroke: null,
        fill: '#5a7a4a',
        antarcticFill: '#c8d8e8',
        greenlandFill: '#c8d8e8',
    },
};

// Load and parse an SVG-backed Earth preset into a list of country paths in
// (lat, lon) radians. Returns null for non-SVG presets (e.g. terrain). The
// returned structure is fed to renderEarthFaceFromSvgPaths (see polyhedral.js)
// to produce per-face canvases at native vector resolution.
//
// SVG-specific: paths sit inside a <g id="positioner" transform="translate(180,90) scale(1,-1)">,
// which makes raw path coordinates equal (lon_deg, lat_deg). Each country
// (<g class="country XXX">) wraps a single <path>.
const _svgPathCache = new Map();
export async function loadEarthSvgPaths(presetIdOrUrl = DEFAULT_EARTH_PRESET) {
    const cacheKey = typeof presetIdOrUrl === 'string' ? presetIdOrUrl : presetIdOrUrl;
    if (_svgPathCache.has(cacheKey)) return _svgPathCache.get(cacheKey);
    const preset = (typeof presetIdOrUrl === 'string' && EARTH_PRESETS[presetIdOrUrl])
        ? EARTH_PRESETS[presetIdOrUrl]
        : { url: presetIdOrUrl };
    if (!preset.svgStyle) return null; // raster preset (terrain), no vector data
    const resp = await fetch(preset.url);
    if (!resp.ok) throw new Error(`SVG fetch ${resp.status}: ${preset.url}`);
    const svgText = await resp.text();
    const doc = new DOMParser().parseFromString(svgText, 'image/svg+xml');
    const svgEl = doc.querySelector('svg');
    if (!svgEl) throw new Error('SVG root <svg> not found');

    // Confirm the positioner transform structure that lets us treat path
    // coords as (lon_deg, lat_deg). Fall back to a generic transform parser
    // if anything looks off.
    let coordToLonLat = null;
    const positioner = doc.querySelector('#positioner');
    if (positioner) {
        const t = positioner.getAttribute('transform') || '';
        const match = t.match(/translate\(\s*([-\d.]+)\s*[, ]\s*([-\d.]+)\s*\)\s*scale\(\s*([-\d.]+)\s*[, ]\s*([-\d.]+)\s*\)/);
        if (match) {
            const tx = parseFloat(match[1]);
            const ty = parseFloat(match[2]);
            const sx = parseFloat(match[3]);
            const sy = parseFloat(match[4]);
            // Inverse to get (lon, lat). The forward map: (x,y)_child → (tx + sx*x, ty + sy*y) in svg space,
            // where svg space's x maps to lon = x_abs - svgW/2, y_abs to lat = svgH/2 - y_abs.
            // Combine: lon_deg = (tx + sx*x) - 180 = (tx-180) + sx*x; lat_deg = 90 - (ty + sy*y) = (90-ty) - sy*y.
            const svgW = parseFloat(svgEl.getAttribute('width'))  || 360;
            const svgH = parseFloat(svgEl.getAttribute('height')) || 180;
            const lonOff = tx - svgW / 2;
            const lonMul = sx;
            const latOff = svgH / 2 - ty;
            const latMul = -sy;
            coordToLonLat = (x, y) => ({
                lon: (lonOff + lonMul * x),
                lat: (latOff + latMul * y),
            });
        }
    }
    if (!coordToLonLat) {
        // Generic fallback: assume viewBox 0 0 W H with no transform.
        const svgW = parseFloat(svgEl.getAttribute('width'))  || 360;
        const svgH = parseFloat(svgEl.getAttribute('height')) || 180;
        coordToLonLat = (x, y) => ({
            lon: (x / svgW) * 360 - 180,
            lat:  90 - (y / svgH) * 180,
        });
    }

    const paths = [];
    for (const g of doc.querySelectorAll('g[class]')) {
        const cls = g.getAttribute('class') || '';
        if (!cls.includes('country')) continue;
        const pathEl = g.querySelector('path');
        if (!pathEl) continue;
        const d = pathEl.getAttribute('d');
        if (!d) continue;
        const pts = parseEarthSvgPathD(d, coordToLonLat);
        if (pts.length === 0) continue;
        paths.push({ className: cls, points: pts });
    }

    if (preset.dedupeEdges) {
        deduplicateSharedEdges(paths);
    }

    const result = {
        presetId: preset.id || presetIdOrUrl,
        paths,
    };
    _svgPathCache.set(cacheKey, result);
    return result;
}

// Mark any line segment whose canonical (lat,lon)-pair key appears in
// more than one country path with `skipFromPrev: true`. Renderers honor
// this flag by moving the pen instead of drawing the segment, so shared
// country borders disappear and only land-water boundaries remain.
function deduplicateSharedEdges(paths) {
    const counts = new Map();
    const keyOf = (a, b) => {
        // 6 decimal places of radians ≈ 36 cm at Earth's surface — way finer
        // than the SVG's 3-decimal-degree precision needs to match.
        const sa = a.lat.toFixed(6) + ',' + a.lon.toFixed(6);
        const sb = b.lat.toFixed(6) + ',' + b.lon.toFixed(6);
        return sa < sb ? sa + '|' + sb : sb + '|' + sa;
    };
    for (const path of paths) {
        const pts = path.points;
        for (let i = 1; i < pts.length; i++) {
            if (pts[i].move) continue;
            const k = keyOf(pts[i - 1], pts[i]);
            counts.set(k, (counts.get(k) || 0) + 1);
        }
    }
    for (const path of paths) {
        const pts = path.points;
        for (let i = 1; i < pts.length; i++) {
            if (pts[i].move) continue;
            const k = keyOf(pts[i - 1], pts[i]);
            if (counts.get(k) > 1) {
                pts[i].skipFromPrev = true;
            }
        }
    }
}

// Parse an SVG path d-attribute (M/L/Z only; the BlankMap-Equirectangular.svg
// uses no curves or arcs) into a flat list of {lat, lon, move} points in
// radians. coordFn maps raw (x, y) from path commands to {lat, lon} in degrees.
function parseEarthSvgPathD(d, coordFn) {
    const pts = [];
    let curX = 0, curY = 0, startX = 0, startY = 0;
    const tokens = d.match(/[MmLlHhVvZz]|-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?/g);
    if (!tokens) return pts;
    const D2R = Math.PI / 180;
    const emit = (x, y, isMove) => {
        const ll = coordFn(x, y);
        pts.push({ lat: ll.lat * D2R, lon: ll.lon * D2R, move: !!isMove });
    };
    let i = 0;
    while (i < tokens.length) {
        const t = tokens[i++];
        if (!/[MmLlHhVvZz]/.test(t)) continue;
        const isCmd = (s) => s !== undefined && /[MmLlHhVvZz]/.test(s);
        switch (t) {
            case 'M': {
                curX = parseFloat(tokens[i++]); curY = parseFloat(tokens[i++]);
                startX = curX; startY = curY;
                emit(curX, curY, true);
                while (i < tokens.length && !isCmd(tokens[i])) {
                    curX = parseFloat(tokens[i++]); curY = parseFloat(tokens[i++]);
                    emit(curX, curY, false);
                }
                break;
            }
            case 'm': {
                curX += parseFloat(tokens[i++]); curY += parseFloat(tokens[i++]);
                startX = curX; startY = curY;
                emit(curX, curY, true);
                while (i < tokens.length && !isCmd(tokens[i])) {
                    curX += parseFloat(tokens[i++]); curY += parseFloat(tokens[i++]);
                    emit(curX, curY, false);
                }
                break;
            }
            case 'L': {
                while (i < tokens.length && !isCmd(tokens[i])) {
                    curX = parseFloat(tokens[i++]); curY = parseFloat(tokens[i++]);
                    emit(curX, curY, false);
                }
                break;
            }
            case 'l': {
                while (i < tokens.length && !isCmd(tokens[i])) {
                    curX += parseFloat(tokens[i++]); curY += parseFloat(tokens[i++]);
                    emit(curX, curY, false);
                }
                break;
            }
            case 'H': {
                while (i < tokens.length && !isCmd(tokens[i])) {
                    curX = parseFloat(tokens[i++]);
                    emit(curX, curY, false);
                }
                break;
            }
            case 'h': {
                while (i < tokens.length && !isCmd(tokens[i])) {
                    curX += parseFloat(tokens[i++]);
                    emit(curX, curY, false);
                }
                break;
            }
            case 'V': {
                while (i < tokens.length && !isCmd(tokens[i])) {
                    curY = parseFloat(tokens[i++]);
                    emit(curX, curY, false);
                }
                break;
            }
            case 'v': {
                while (i < tokens.length && !isCmd(tokens[i])) {
                    curY += parseFloat(tokens[i++]);
                    emit(curX, curY, false);
                }
                break;
            }
            case 'Z': case 'z': {
                if (curX !== startX || curY !== startY) {
                    emit(startX, startY, false);
                }
                curX = startX; curY = startY;
                break;
            }
        }
    }
    return pts;
}

// Smaller than Earth's 256 - the MW coverage map is repainted every frame so
// per-face pixel cost has to stay bounded. 96 looks acceptable when blitted up
// to face displays of a few hundred pixels.
const MW_RENDER_SIZE = 96;

// One-time extraction of the processed-texture ImageData so per-frame
// re-renders don't re-call getImageData (which allocates and copies).
export function extractMilkyWayTextureData(mwCanvas) {
    const tctx = mwCanvas.getContext('2d');
    try {
        return tctx.getImageData(0, 0, mwCanvas.width, mwCanvas.height);
    } catch (e) {
        throw new Error('Milky Way texture is CORS-tainted; cannot read pixels.');
    }
}

// Allocate per-face MW canvases (geometry only - no pixel fill). Each canvas
// stores its own reusable ImageData buffer so the per-frame fill avoids
// allocations. polygonCorners is precomputed since it only depends on face
// geometry, not on the time-varying rotation.
export function allocateMilkyWayFaceCanvases(faces) {
    return faces.map(face => {
        const size = MW_RENDER_SIZE;
        const c = document.createElement('canvas');
        c.width = c.height = size;
        const ctx = c.getContext('2d');
        c._mwImgData = ctx.createImageData(size, size);
        const half = size / 2;
        const pxRadius = half * 0.95;
        const faceFirstAngle = Math.atan2(face.vertices2D[0].v, face.vertices2D[0].u);
        const rotation = Math.PI / 2 - faceFirstAngle;
        const cosR = Math.cos(rotation), sinR = Math.sin(rotation);
        const scale = pxRadius / face.faceCircumradius;
        c._mwRot = { cosR, sinR, scale };
        c.polygonCorners = face.vertices2D.map(({ u, v }) => {
            const uR = u * cosR - v * sinR;
            const vR = u * sinR + v * cosR;
            return { x: half + scale * uR, y: half - scale * vR };
        });
        return c;
    });
}

// Per-frame MW fill: rewrite every canvas's pixels using the current
// observer-to-galactic rotation. Caller passes the source ImageData (once)
// and the rotation (every frame).
export function fillMilkyWayFaces(canvases, faces, texData, obsToGalMatrix) {
    for (let i = 0; i < canvases.length; i++) {
        fillMwFace(canvases[i], faces[i], texData, obsToGalMatrix);
    }
}

function fillMwFace(c, face, texData, M) {
    const size = c.width;
    const half = size / 2;
    const { cosR, sinR, scale } = c._mwRot;
    const imgData = c._mwImgData;
    const pixels = imgData.data;
    const tw = texData.width, th = texData.height;
    const texPixels = texData.data;
    const verts2D = face.vertices2D;
    const cx = face.center.x, cy = face.center.y, cz = face.center.z;
    const bUx = face.basisU.x, bUy = face.basisU.y, bUz = face.basisU.z;
    const bVx = face.basisV.x, bVy = face.basisV.y, bVz = face.basisV.z;

    for (let py = 0; py < size; py++) {
        const vR = (half - py) / scale;
        for (let px = 0; px < size; px++) {
            const uR = (px - half) / scale;
            const u = uR * cosR + vR * sinR;
            const v = -uR * sinR + vR * cosR;
            const outIdx = (py * size + px) * 4;

            if (!pointInPolygon(u, v, verts2D)) {
                pixels[outIdx + 3] = 0;
                continue;
            }

            const xx = cx + u * bUx + v * bVx;
            const yy = cy + u * bUy + v * bVy;
            const zz = cz + u * bUz + v * bVz;
            const len = Math.sqrt(xx * xx + yy * yy + zz * zz);
            const ox = xx / len, oy = yy / len, oz = zz / len;

            const gx = M[0] * ox + M[1] * oy + M[2] * oz;
            const gy = M[3] * ox + M[4] * oy + M[5] * oz;
            const gz = M[6] * ox + M[7] * oy + M[8] * oz;

            const lat = Math.asin(gy < -1 ? -1 : (gy > 1 ? 1 : gy));
            const lon = Math.atan2(gz, gx);
            let tx = (lon / (2 * Math.PI) + 0.5) * tw;
            let ty = (0.5 - lat / Math.PI) * th;
            if (tx < 0) tx = 0; else if (tx >= tw) tx = tw - 1; else tx |= 0;
            if (ty < 0) ty = 0; else if (ty >= th) ty = th - 1; else ty |= 0;

            const ti = (ty * tw + tx) * 4;
            pixels[outIdx]     = texPixels[ti];
            pixels[outIdx + 1] = texPixels[ti + 1];
            pixels[outIdx + 2] = texPixels[ti + 2];
            pixels[outIdx + 3] = texPixels[ti + 3];
        }
    }

    c.getContext('2d').putImageData(imgData, 0, 0);
}

// Backward-compat: the old API allocated + filled in one shot. Now built on
// top of the new split.
export function preRenderMilkyWayFaces(faces, mwCanvas, obsToGalMatrix) {
    const texData = extractMilkyWayTextureData(mwCanvas);
    const canvases = allocateMilkyWayFaceCanvases(faces);
    fillMilkyWayFaces(canvases, faces, texData, obsToGalMatrix);
    return canvases;
}

// `sphereOrientation` is an optional 3x3 row-major rotation matrix applied to
// each pixel's face direction before treating it as geographic. The same
// matrix is applied to stars on the celestial side (via the obsToGeo
// composition in main.js), so Earth and stars always read the polyhedron the
// same way. Pass null/undefined for identity (no extra rotation).
export function preRenderEarthFaces(faces, earthImage, sphereOrientation = null) {
    const tex = document.createElement('canvas');
    tex.width = earthImage.naturalWidth;
    tex.height = earthImage.naturalHeight;
    const tctx = tex.getContext('2d');
    tctx.drawImage(earthImage, 0, 0);
    let texData;
    try {
        texData = tctx.getImageData(0, 0, tex.width, tex.height);
    } catch (e) {
        throw new Error('Earth texture is CORS-tainted; cannot read pixels. Image must be served with Access-Control-Allow-Origin.');
    }
    return faces.map(f => renderEarthFace(f, texData, sphereOrientation));
}

function renderEarthFace(face, texData, sphereOrientation) {
    const size = RENDER_SIZE;
    const c = document.createElement('canvas');
    c.width = c.height = size;
    const ctx = c.getContext('2d');
    const imgData = ctx.createImageData(size, size);

    const half = size / 2;
    const pxRadius = half * 0.95;

    // Same orientation convention as modes B/C: vertex 0 at canvas-up.
    const faceFirstAngle = Math.atan2(face.vertices2D[0].v, face.vertices2D[0].u);
    const rotation = Math.PI / 2 - faceFirstAngle;
    const cosR = Math.cos(rotation), sinR = Math.sin(rotation);
    const scale = pxRadius / face.faceCircumradius;

    const tw = texData.width, th = texData.height;
    const texPixels = texData.data;
    const pixels = imgData.data;

    for (let py = 0; py < size; py++) {
        for (let px = 0; px < size; px++) {
            // canvas (px, py) -> rotated face coords (uR, vR) -> face local (u, v)
            const uR = (px - half) / scale;
            const vR = (half - py) / scale;
            const u = uR * cosR + vR * sinR;
            const v = -uR * sinR + vR * cosR;

            if (!pointInPolygon(u, v, face.vertices2D)) {
                pixels[(py * size + px) * 4 + 3] = 0;
                continue;
            }

            // 3D point on face plane, normalized to unit direction.
            const xx = face.center.x + u * face.basisU.x + v * face.basisV.x;
            const yy = face.center.y + u * face.basisU.y + v * face.basisV.y;
            const zz = face.center.z + u * face.basisU.z + v * face.basisV.z;
            const len = Math.sqrt(xx * xx + yy * yy + zz * zz);
            let nx = xx / len, ny = yy / len, nz = zz / len;

            // Optional sphere-orientation rotation applied to the face
            // direction before reading as geographic; matches the matrix
            // pre-composed onto obsToGeo for the star pipeline.
            if (sphereOrientation) {
                const R = sphereOrientation;
                const rx = R[0]*nx + R[1]*ny + R[2]*nz;
                const ry = R[3]*nx + R[4]*ny + R[5]*nz;
                const rz = R[6]*nx + R[7]*ny + R[8]*nz;
                nx = rx; ny = ry; nz = rz;
            }
            const lat = Math.asin(ny < -1 ? -1 : (ny > 1 ? 1 : ny));
            const lon = Math.atan2(nz, nx);
            let tx = (lon / (2 * Math.PI) + 0.5) * tw;
            let ty = (0.5 - lat / Math.PI) * th;
            if (tx < 0) tx = 0; else if (tx >= tw) tx = tw - 1; else tx |= 0;
            if (ty < 0) ty = 0; else if (ty >= th) ty = th - 1; else ty |= 0;

            const ti = (ty * tw + tx) * 4;
            const j = (py * size + px) * 4;
            pixels[j]     = texPixels[ti];
            pixels[j + 1] = texPixels[ti + 1];
            pixels[j + 2] = texPixels[ti + 2];
            pixels[j + 3] = 255;
        }
    }

    ctx.putImageData(imgData, 0, 0);

    // Attach the offscreen-frame polygon corners so the display side can build
    // the affine transform without re-running the rotation math.
    c.polygonCorners = face.vertices2D.map(({ u, v }) => {
        const uR = u * cosR - v * sinR;
        const vR = u * sinR + v * cosR;
        return { x: half + scale * uR, y: half - scale * vR };
    });

    return c;
}

function pointInPolygon(x, y, poly) {
    let inside = false;
    for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
        const xi = poly[i].u, yi = poly[i].v;
        const xj = poly[j].u, yj = poly[j].v;
        if (((yi > y) !== (yj > y)) && (x < (xj - xi) * (y - yi) / (yj - yi) + xi)) {
            inside = !inside;
        }
    }
    return inside;
}

// 2x3 affine that maps the first 3 srcPts to the first 3 dstPts. For two
// similar polygons we only need 3 corresponding vertices; the others are
// constrained by the similarity. Returns null if degenerate.
export function affineFromPolygons(srcPts, dstPts) {
    const s0 = srcPts[0], s1 = srcPts[1], s2 = srcPts[2];
    const d0 = dstPts[0], d1 = dstPts[1], d2 = dstPts[2];
    const det = (s1.x - s0.x) * (s2.y - s0.y) - (s2.x - s0.x) * (s1.y - s0.y);
    if (Math.abs(det) < 1e-10) return null;
    const a = ((d1.x - d0.x) * (s2.y - s0.y) - (d2.x - d0.x) * (s1.y - s0.y)) / det;
    const c = ((s1.x - s0.x) * (d2.x - d0.x) - (s2.x - s0.x) * (d1.x - d0.x)) / det;
    const e = d0.x - a * s0.x - c * s0.y;
    const b = ((d1.y - d0.y) * (s2.y - s0.y) - (d2.y - d0.y) * (s1.y - s0.y)) / det;
    const d = ((s1.x - s0.x) * (d2.y - d0.y) - (s2.x - s0.x) * (d1.y - d0.y)) / det;
    const f = d0.y - b * s0.x - d * s0.y;
    return { a, b, c, d, e, f };
}
